name: framework_as
description: Framework Modular Empresarial
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2

  flutter_svg: ^2.0.10

  fl_chart: ^0.68.0

  flutter_colorpicker: ^1.0.3
  provider: ^6.1.2
  path_provider: ^2.1.0

  cupertino_icons: ^1.0.6
  intl: ^0.18.1
  crypto: ^3.0.3
  file_picker: ^8.0.0


  # Database
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.0
  path: ^1.9.0

  # Storage
  shared_preferences: ^2.2.2
  pdf: ^3.11.3
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/login/
    - assets/login/icons/

  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Regular.ttf
        - asset: assets/fonts/Sora-ExtraBold.ttf
          weight: 800

    - family: Share
      fonts:
        - asset: assets/fonts/Share-Regular.ttf
        - asset: assets/fonts/Share-Bold.ttf
          weight: 700


  